### PR TITLE
Added Customer Model

### PR DESCRIPTION
**Pull request by kbmaddineni**
Added customer model and added the "Customers" maintenance to the admin page.

### CODE REVIEW

**Comment by kbmaddineni** [comment]
> Added customer model and added the "Customers" maintenance to the admin page.

**Comment by kbmaddineni** [comment]
I accidentally closed the pull request. I am reopening it now.

**Comment by kbmaddineni** [comment]
@sjmarshall07, please review this pull request to see all your changes are included and merge the pull request.

**Comment by sjmarshall07** [comment]
@kbmaddineni - how do I just pull this pull request down to run and validate?

**Comment by sjmarshall07** [comment]
If you're able to figure it out then if you run the application and see the customers in the admin menu, then yes, it will have everything. I've been diggin in GIT and pycharm for some time now and cannot figure out how to pull down this pull request to run and validate

**Pull request merged**
